DROP TABLE IF EXISTS CLUBS CASCADE;

CREATE TABLE IF NOT EXISTS CLUBS(
    CLUB_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    LOCATION VARCHAR(255) NOT NULL,
    COUNT INT DEFAULT 0,
    MAX_CAPACITY INT DEFAULT 0,
    GENRE VARCHAR(255),
    YELLOWTHRESHOLD INT DEFAULT 0
    
);

INSERT INTO CLUBS(NAME, LOCATION, COUNT,MAX_CAPACITY,GENRE,YELLOWTHRESHOLD) VALUES
('Club Arcane', 'Toronto',0,100,'EDM', 70),
('Club Underground','LA',0,50,'Hip-Hop',30),
('Club Soda','Chicago',0,20,'pop',12),
('Studio 52','Lagos',0,52,'Afro-beats',32)

ON CONFLICT DO NOTHING;